# Official Nginx image (Yes, in this article I always use the `latest`. Kill me!)
FROM nginx:latest
 
# Copy Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf
 
# Expose port 80
EXPOSE 80

