basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: backend of the event management app.
  title: Squid Tech API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: Pasword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login endpoint
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: example@gmail.com
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: password
        in: body
        name: Password
        required: true
        schema:
          type: string
      - description: aymen charfaoui
        in: body
        name: Name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Registration endpoint
      tags:
      - auth
swagger: "2.0"
